app:
  env: dev
  name: go-mall
  log:
    path: "/tmp/applogs/go-mall.log"
    max_size: 1
    max_age: 60
  pagination:
    default_page_size: 20
    max_page_size: 100

database:
  type: mysql
  master:
    dsn: root:Admin#098@tcp(127.0.0.1:30306)/go_mall?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 30000000000 # 30s
  slave:
    dsn: root:Admin#098@tcp(127.0.0.1:30306)/go_mall?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000

redis:
  addr: 127.0.0.1:31379
  username: wuvikr
  password: Admin#098
  pool_size: 10
  db: 0